### ISSUE TITLE
 how can I add separate view controller for each progress

### ISSUE THREAD

**Issue by prakhila** [amratab/FlexibleSteppedProgressBar#14]

**Comment by prakhila** [comment]
hi... thank you in advance ,I'm fresher in swift ,this library works for me its really awesome ..I want to add separate view controllers for each steps

**Comment by abdulla-allaith** [comment]
This library does not cover the "page switching" part of the progress.
It focuses on delivering a progress bar solution, which it excels at! 👏 
Possible solutions to your issue:

A) Use a `UIContainerView` that hosts a view controller. Change the displayed controller on `didSelectItemAtIndex` delegate function (or programmatically).

B) Use a `UIScrollView`, append multiple custom views to it. Change the `contentOffset` on `didSelectItemAtIndex` delegate function (or programmatically). If you have a button to move to next step, you can set the scrollview's `isScrollEnabled` to false.

Personally, I am using solution B which provides me with a nice "next page" animation on switching to next steps. Feel free to ask me for further clarification, but since this is out of the project's scope, I think @amratab can close it.

**Comment by amratab** [comment]
Thanks @abdulla-allaith for resolving this.
